# Generated by Django 4.1.7 on 2023-03-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.CharField(blank=True, choices=[('adcd', 'aDAS'), ('SA', 'as'), ('SA', 'as')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='pending',
            field=models.CharField(blank=True, choices=[('adcd', 'aDAS'), ('SA', 'as'), ('SA', 'as')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='trash',
            field=models.CharField(blank=True, choices=[('adcd', 'aDAS'), ('SA', 'as'), ('SA', 'as')], max_length=200, null=True),
        ),
    ]
