# Generated by Django 4.1.7 on 2023-03-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_done_todo_pending_todo_trash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
