# Generated by Django 4.1.7 on 2023-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('todo', models.CharField(blank=True, choices=[('adcd', 'aDAS'), ('SA', 'as'), ('SA', 'as')], default='todo', max_length=200, null=True)),
                ('pending', models.CharField(blank=True, choices=[('adcd', 'aDAS'), ('SA', 'as'), ('SA', 'as')], max_length=200, null=True)),
                ('done', models.CharField(blank=True, choices=[('adcd', 'aDAS'), ('SA', 'as'), ('SA', 'as')], max_length=200, null=True)),
                ('trash', models.CharField(blank=True, choices=[('adcd', 'aDAS'), ('SA', 'as'), ('SA', 'as')], max_length=200, null=True)),
            ],
        ),
    ]
