# Generated by Django 4.1.7 on 2023-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_doing_done_trash_rename_task_todo_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doing',
        ),
        migrations.DeleteModel(
            name='Done',
        ),
        migrations.DeleteModel(
            name='Trash',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.AddField(
            model_name='todo',
            name='doing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo',
            field=models.CharField(blank=True, default='todo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='trash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
