# Generated by Django 4.1.7 on 2023-03-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_doing_delete_done_delete_trash_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
