# Generated by Django 4.1.7 on 2023-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0007_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(blank=True, max_length=200, null=True)),
                ('doing', models.CharField(blank=True, max_length=200, null=True)),
                ('done', models.CharField(blank=True, max_length=200, null=True)),
                ('trash', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
