# Generated by Django 4.1.7 on 2023-03-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
