# Generated by Django 4.1.7 on 2023-03-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
