# Generated by Django 4.1.7 on 2023-03-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0011_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.JSONField()),
                ('doing', models.CharField(max_length=100)),
                ('done', models.CharField(max_length=100)),
                ('trash', models.CharField(max_length=100)),
            ],
        ),
    ]
