# Generated by Django 4.1.7 on 2023-03-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_todo_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='doing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='trash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
