# Generated by Django 4.1.7 on 2023-03-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='done',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
