# Generated by Django 4.1.7 on 2023-03-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_doing_created_at_alter_done_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doing',
        ),
        migrations.DeleteModel(
            name='Done',
        ),
        migrations.DeleteModel(
            name='Trash',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('doing', 'doing'), ('pending', 'pending'), ('trash', 'trash')], default='pending', max_length=25),
        ),
    ]
